#!/bin/bash
#Author : Amirreza Firoozi
#Author : Carsten Brueggenolte
#name : wttr
#Update 1.30: change config dir to $HOME/.config/wttr to go in line with other configuration files
#Update 1.30: changed default city filename to 'default-city.txt'


wttr_ver="1.30" #define script version
if [ -f "$HOME/.config/wttr/default-city.txt" ];then #check if user set default city or not . if user did load it to variable def
    cd $HOME/.config/wttr
    def=$(cat default-city.txt) 
elif [ ! -d $HOME/.config/wttr ];then #if he/she didn`t make a blank file
    mkdir ".config/wttr"  2>/dev/null
    echo "" > default-city.txt 
    def=""
fi
if [ "$#" == "0" ] && [ "$def" == "" ];then
    echo -e "You have not entered any parameters \n Needs help? try wttr -h"
elif [ "$#" -gt "2" ];then
   
    echo -e "too many parameters. \n Needs help? try wttr -h"
else
    case $1 in 
    "-h") #showing help
        echo -e "This is a simple app to check weather condition."
        echo -e "wttr is under GPL3 License. source is available on Github : https://github.com/cblte/wttr" 
        echo -e "Created by : Carsten Brueggenolte"
        echo -e "A big thank you goes to: Amirreza Firoozi - he wrote the initial script (https://github.com/AmirrezaFiroozi/wttr)"
        echo -e ""
        echo -e "Write wttr {your city name} to check the  weather condition of your city. example : wttr cologne"
        echo -e "    -m for photo of moon"
        echo -e "    -h for some help (this page)"
        echo -e "    -v for script version"
        echo -e "    -i to install curl which is necessary for script to run correctly"
        echo -e "    -rm to remove the script :("
        echo -e "    -sdef to define a city as your default city"
        echo -e ""
        echo -e "Any bugs? Any suggestions? Contact information at https://zn80.net/impressum" 
    ;;
    "-v")
        echo -e "wttr_VERSION is : "$wttr_ver" "
    ;;
    "-m")
        curl http://wttr.in/moon
    ;;
    "-i")
        sudo apt install curl
    ;;
    "-rm") 
        read -p "Do you Really want to remove wttr?(y/n)" response
        if [ "$response" == "y" ];then
            cd /usr/bin
            sudo rm -R "wttr"    2>/dev/null 
            if [ -d "$HOME/.config/wttr" ];then
                sudo rm -d "$HOME/.config/wttr" 2>/dev/null
            fi
            echo -e "Script has deleted :("
        else
            echo -e "Opration canceled"
        fi
    ;;
    "-sdef") # set the default city
        if [ ! -d $HOME/.config/wttr ];then
            cd $HOME
            mkdir -p ".config/wttr" 2>/dev/null 
        fi    
        if [ "$#" == "2" ];then
 	        cd $HOME/.config/wttr
            echo "$2" > default-city.txt
	        echo -e ""
            echo -e "Done. Set '$2' as your default city. You can check its weather condition by typing only wttr Since now :)" 
        else
            read -p " Enter your city name to set as the default city (example : cologne) : " def
            if [ "$def" == "" ] && [ "$#" -ls "2" ];then
                echo "you did NOT enter anything ..."
            else
                cd $HOME/.config/wttr
                echo $def > default-city.txt
	            echo -e ""
                echo -e "Done. Set '$def' as your default city. You can check its weather condition by typing only wttr Since now :)" 
            fi
        fi #end of the second if
    ;;
    "")
        cd $HOME
        curl http://wttr.in/"$def"
    ;;
    *)
    
    curl http://wttr.in/"$1"
      
    ;;
  esac
fi


